### ISSUE TITLE
Review before announcement

### ISSUE THREAD

**Issue by tdd** [deliciousinsights/brunch-guide#1]
Calling all of "Brunch Core" on deck: @paulmillr, @es128, @nikgraf, @tosh!

Hey guys,

Paul had noticed my FR article in early March, and tweeted about it ("It's like a book on Brunch!"). I got numerous requests to make it more widely available and less intimidating to read (not a single page, that is). So I bit the bullet and turned it into a bona-fide guide on GitHub, using 12 "chapters". And I made it available in English, too.

Before announcing it more widely (and I do hope you'll like it enough that you'll announce it through Brunch channels, perhaps even link to it from relevant places in Brunch's docs/site), I'd really like you guys to comb through it and make sure I didn't say something horribly incorrect.

Feel free to fork and PR, or just to comment on this issue, to materialize your feedback.

Looking forward to hearing from you!

**Comment by es128** [comment]
Very cool! Perhaps we can also adapt this to finally fill in our section at https://github.com/tooling/book-of-modern-frontend-tooling

**Comment by es128** [comment]
Starting to read through it now. First of all, the content is excellent and flows well (so far). I'll comment as I encounter parts I have thoughts on:

https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter01-whats-brunch.md#then-why-do-i-only-ever-hear-about-the-others
I have some alternate theories on why Brunch is less popular to augment the inferior marketing point you make here, which I do agree with. We could potentially discuss at some point, but it's not too important.

https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter02-getting-started.md#getting-started-with-brunch
You may end up covering this later, but I think it's often a good idea to install Brunch globally **and** locally. The brunch package acts kind of like grunt-cli and grunt combined. I believe gulp also generally behaves this way and that they encourage global+local installs.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter02-getting-started.md#should-i-use-a-skeleton
I've had a thought that for Brunch 2.0 perhaps the skeleton paradigm should be shifted to actually begin leveraging Yeoman to allow the community to define more comprehensive generators for Brunch projects. I haven't looked into it too deeply though. But this goes along with some of my thinking that rather than "compete" Brunch should move toward a direction of being able to seamlessly integrate with other parts of the js ecosystem.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter03-conventions-and-defaults.md#configuration-files
You refer to some deprecated stuff here, but you did say at the top which version of brunch this guide targets, so I guess it's ok.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter04-starting-from-scratch.md#our-first-build
Ok in this section you're actually exposing a misunderstanding about the nature of globally/locally installed Brunch. [As you can see here](https://github.com/brunch/brunch/blob/master/bin/brunch) as long as the global brunch is v1.7.1 or later, calling the global CLI commands will actually execute the version of brunch (any version) that is installed locally in the project, if present.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter04-starting-from-scratch.md#split-targets
The anchor in the anymatch link here needs an extra dash to go down to the top of the readme (which is what I think you were going for). Or perhaps a less brittle way of handling it would be to just link directly to https://github.com/es128/anymatch/blob/master/README.md.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter05-using-third-party-registries.md#using-third-party-module-registries
Looks like there's a desire to provide an ability to module-wrap specified vendor/bower files. This should probably be opened as an issue in Brunch - not sure I've ever seen anyone explicitly ask for it before.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter06-a-shot-at-templating.md#a-shot-at-templating
I'd suggest avoiding the gendered word "guys" here.

**Comment by paulmillr** [comment]
Nikgraf and tosh are not active maintainers BTW — so no point in mentioning them.

**Comment by tdd** [comment]
Hey Elan,

> I have some alternate theories on why Brunch is less popular to augment the inferior marketing point you make here, which I do agree with. We could potentially discuss at some point, but it's not too important.

I'm absolutely interested in your theories on this. The marketing point is not very strong, I agree, and the docs one is stronger but sad :neutral_face: 

> You may end up covering this later, but I think it's often a good idea to install Brunch globally and locally. The brunch package acts kind of like grunt-cli and grunt combined. I believe gulp also generally behaves this way and that they encourage global+local installs.

Now that I understand the global CLI defers to local module, this makes total sense!  Absolutely need to rewrite that part and stress this point, thank you! :smile: 

Leveraging Yeoman for actual interactive generation: :+1: 

> You refer to some deprecated stuff here, but you did say at the top which version of brunch this guide targets, so I guess it's ok.

Well, 1.7.20 remains the latest public version, right now. Can you list what's deprecated and why, so I can anticipate and augment the text with info on this?

> Looks like there's a desire to provide an ability to module-wrap specified vendor/bower files. This should probably be opened as an issue in Brunch - not sure I've ever seen anyone explicitly ask for it before.

Actually there's not. For me the future lies with npm integration, not Bower. And it would be weird for existing Bower users to suddenly get their Bower code wrapped, **especially** because many Bower-distributed files are not ready for it.

> I'd suggest avoiding the gendered word "guys" here.

Oh, did one get through my filter? Dammit!

> Nikgraf and tosh are not active maintainers BTW — so no point in mentioning them.

Duly noted.  Didn't check the contribution data, just picked the list from the Brunch org page.

All fixed and pushed!  Thanks a ton for the comments already, looking forward to more!

**Comment by es128** [comment]
Using `config.*` as the config filename is deprecated, and the `-c`/`--config` CLI switch has been deprecated in favor of `-e`/`--env` and `overrides`.

For the bower module wrapping - I wasn't suggesting automatically wrapping everything. My thought was providing a new config option to explicitly list vendor files that you want Brunch to apply module wrapping for you. That way you still get the advantage of package manager version management without having to copy into your `app` files to get this behavior.

**Comment by tdd** [comment]
> Using config.\* as the config filename is deprecated

Cool, I'll strip that right now.

> the -c/--config CLI switch has been deprecated in favor of -e/--env and overrides.

Oh, is it?  OK, I guess that makes sense.  Since that impacts file structure, I'll probably remove it now too, as this will be that much less work to do when getting to 1.8+.

> My thought was providing a new config option to explicitly list vendor files that you want Brunch to apply module wrapping for you

That would definitely be useful, although personally what I can't wait for (and Paul told me you guys were almost done with that) is npm integration, which just kills Bower usefulness in my view. It also kills 99% of the need for Browserify, which is neat, as browserify-brunch is rather kludgy. Any ETA on that, btw?

**Comment by es128** [comment]
There's a [1.8.0-pre](https://github.com/brunch/brunch/commit/de246fafa099c55c4eb45b7a1c6618a3671f63ea) you can try.

At this point there's stuff being published to npm that isn't CommonJS (like some jquery plugins I think), so I think the kind of thing I'm describing may still end up being useful - possibly necessary.

**Comment by nikgraf** [comment]
I'm not involved anymore, but I took a brief look & it looks great. What I personally like is if a technical book provide a short summary after each chapter. It helps to rewind how all the things you learned and how to make sense of them together. I hope that helps.

Keep up the good work!

**Comment by nikgraf** [comment]
I'm not involved anymore, but I took a brief look & it looks great. What I personally like is if a technical book provide a short summary after each chapter. It helps to rewind how all the things you learned and how to make sense of them together. I hope that helps.

Keep up the good work!

**Comment by nikgraf** [comment]
I'm not involved anymore, but I took a brief look & it looks great. What I personally like is if a technical book provide a short summary after each chapter. It helps to rewind how all the things you learned and how to make sense of them together. I hope that helps.

Keep up the good work!

**Comment by nikgraf** [comment]
I'm not involved anymore, but I took a brief look & it looks great. What I personally like is if a technical book provide a short summary after each chapter. It helps to rewind how all the things you learned and how to make sense of them together. I hope that helps.

Keep up the good work!

**Comment by nikgraf** [comment]
I'm not involved anymore, but I took a brief look & it looks great. What I personally like is if a technical book provide a short summary after each chapter. It helps to rewind how all the things you learned and how to make sense of them together. I hope that helps.

Keep up the good work!

**Comment by paulmillr** [comment]
I'll review it today & tomorrow. Maybe we can push 1.8 before the guide is published.

**Comment by tdd** [comment]
Ha! If you guys do, I'll have to go through the changelog / relnotes to adjust. Please please pleaaaaase tell me first-class npm/node_modules integration is ready :wink: :pray:

**Comment by es128** [comment]
@tdd It's in there, but it's not well vetted. If you could try 1.8.0-pre and provide feedback, that would be great.

//cc @yavorsky

**Comment by paulmillr** [comment]
It's working. Needs a few tweaks though.

**Comment by tdd** [comment]
Will do!

## 

Christophe Porteneuve
tdd@tddsworld.com

**Comment by tdd** [comment]
At the risk of sounding daft: where is 1.8.0-pre? Doesn't show up in `npm show brunch`, nor do I see a branch, tag or release in brunch/brunch.  Do you just mean the current master?

**Comment by es128** [comment]
Actually yeah @paulmillr did you just bump the version in package.json? We should add the git tag and do a tagged release to npm: `npm publish . --tag pre` (don't forget the `.` and apparently semver-valid versions aren't allowed to be used as npm tags anymore, which I just learned when publishing chokidar@1.0.0-rc6)

@tdd for the moment, current master should be sufficient for playing with it

**Comment by paulmillr** [comment]
I think it's simple enough to do `npm install -g brunch/brunch` — that would install current `master`. Can we do this for now?

**Comment by es128** [comment]
sure - it's fine for now

**Comment by yavorsky** [comment]
@es128 Npm is working. Maybe need some work with performance, and ability to replace node's shims with user's custom shims (for now it's ignoring module if it's contains node modules like `fs` or `path`), but everything else - nice.

**Comment by es128** [comment]
getting back to where I left off...

https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter08-production-builds.md
The `overrides.production` you copied in from the docs actually reflects the defaults, so if you agree with those settings, no need to specify anything. Or you can override partially, such as `overrides: production: sourceMaps: true`

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter09-watcher.md
lol @ "if you like it unreadable"

apparently that's how I like it

**Comment by es128** [comment]
Btw regarding the watcher concerns described on that page - chokidar 1.0.0 will be published sometime next week most likely, at which point I'll make sure to also push a brunch 1.7.21 just to backport in all the fixes and benefits that have been addressed since chokidar 0.12.x

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter10-web-server.md
This page could also mention the ability to have Brunch run a non-node.js server as a child process.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter11-plugins.md

`s/fine/find/`

---

> The easiest way to do that for the first time is with `npm install --save-dev`, and the easiest way from an existing package.json is through a simple `npm install`

This sentence would probably be a little clearer with something like `npm install --save-dev <pluginName>`

---

> looking for any module whose name contains “brunch”

I don't think it actually cares that "brunch" is in the module name, just the `brunchPlugin` property (which you did also mention)

---

Your plugins summary is amazing and clear. We totally need to link to this or adopt this on the site and/or somewhere in the official docs, it's much better than the listings that exist today. I kind of wish it appeared earlier in the book.

---

auto-reload-brunch does do seamless css injection btw, it only refreshes on javascript changes

---

This section is already long - I'd suggest breaking out the part about authoring a custom extension to its own page.

---

The thing about major/minor version alignment - your description that this has been a convention is accurate, but the concept is very problematic and has caused a lot of semver violations in the Brunch ecosystem (including in Brunch itself). I was thinking Brunch 2.0 would ditch this idea and come up with a better solution for indicating compatibility. I'm just finding out here that `peerDependencies` is going to be deprecated - I had thought maybe it would be useful for this.

**Comment by es128** [comment]
https://github.com/deliciousinsights/brunch-guide/blob/master/content/en/chapter12-conclusion.md
haha I starred it when you told me to

Ok... review done. 

@tdd the Brunch ecosystem has been sorely lacking a guide this well-written and comprehensive, and you have my sincerest thanks for having put in the effort to contribute it.

**Comment by tdd** [comment]
Hey Elan,

> The overrides.production you copied in from the docs actually reflects the defaults, so if you agree with those settings, no need to specify anything. Or you can override partially, such as overrides: production: sourceMaps: true

Good point, but then why on Earth do the _official_ docs use such an example?!  I'll change to sourceMaps enablement, for sure.

> apparently that's how I like it

Haha, me too actually :wink: But I wouldn't use that in my articles or first-time demos, readability ftw!

Re: Chokidar: **man** I hope this gets better.  I've had _systematic issues_ on Windows (and from 1.7.20+ sometimes on Linux/OSX too) in my training classes. Tarnishes the image of the tool in people's minds. Still, apparently Chokidar is as good as it gets in the Node world for watching, so the state I've seen so far kinda says "so the best the Node world can do is still not enough." Looking forward to Chokidar 1.0 very much!

> This page could also mention the ability to have Brunch run a non-node.js server as a child process.

Wut?! Wasn't at all aware of this. The `command` setting is very discreet in the docs :wink: How long's it been there? I should totally mention this.

Re: `--save-dev` clarity: agreed, this needs rephrasing.

> I don't think it actually cares that "brunch" is in the module name, just the brunchPlugin property (which you did also mention)

I was thrown off by https://github.com/brunch/brunch/blob/master/src/helpers.coffee#L379 but according to https://github.com/brunch/brunch/blob/master/src/watch.coffee#L335 you're very right :unamused: 

> auto-reload-brunch does do seamless css injection btw, it only refreshes on javascript changes

Oh, was convinced otherwise. Need to double-check the code and adjust.

> This section is already long - I'd suggest breaking out the part about authoring a custom extension to its own page.

I'm not sure… This feels like artificial splitting of an otherwise single-topic chapter. The rest of the guide doesn't have "subchapters" either, so a "subchapter" here would look weird. But perhaps an in-chapter TOC at the beginning so people can easily skip to the create-your-own part?

Re: version sync: should we just _not_ mention it, and just stay with `peerDependencies` for now (still saying it's on its way to deprecation)? Which also means just going with, say 1.0.0 initial version for plugins? It's really a semver-vs-sync-info issue. peerDeps helps, I guess, until they're removed.

Thanks a lot for your accolade. I'm super glad you like the guide. I'll work on the adjustments described above tomorrow in both languages and push that back up.

Looking forward to @paulmillr's review, too.

Cheers,

**Comment by es128** [comment]
> why on Earth do the official docs use such an example

Because it's a ready-made sane example that represents object structure, etc. But yes, it ought to mention that this is the same as the defaults.

>  How long's it been there?

Here's the origin of `command`: https://github.com/brunch/brunch/pull/863

> I was thrown off by https://github.com/brunch/brunch/blob/master/src/helpers.coffee#L379

That's actually new code involved in the `node_modules` support - ensuring plugins don't end up being built into the front-end. Probably could be refined some.

> Need to double-check the code and adjust

https://github.com/brunch/auto-reload-brunch/blob/master/index.js#L99
https://github.com/brunch/auto-reload-brunch/blob/master/vendor/auto-reload.js#L21-L29

> an otherwise single-topic chapter

Hmm, I think I perceive plugin authoring and consumption of the plugin ecosystem as distinct topics. At the time I was reading it I was surprised after getting through all that info on existing plugins to scroll down right into another big section on authoring. But nbd

> should we just not mention it

I wouldn't say that - it's still the convention as of now. I was just raising for discussion the fact that we're going to need to come up with a better way in the future.

**Comment by es128** [comment]
@tdd What do you think of the idea of transferring this repo into the brunch org to make it that much more "official"? We should be able to set it up so you retain full maintenance rights.

**Comment by tdd** [comment]
I'm fine with that. Such an option is one of the reasons I haven't publicized this repo just yet. I'll do some more copy editing this morning to include all we've talked about so far, then transfer.

**Comment by tdd** [comment]
It's all been pushed. I'm transferring ownership to the Brunch org. I look forward to you adjusting this so I retain full rights on that repo!

**Comment by tdd** [comment]
Ha ha, silly of me: I **obviously** can't transfer this, as I'd need admin rights on the Brunch org!

https://help.github.com/articles/transferring-a-repository/#transferring-between-organizations

So I'm giving you (Paul and Elan) admin rights on _this_ repo, so you can transfer it out to the Brunch org. Then please create a Guide (or Docs) Team in there, put me in it, and give it admin rights on the new repo.

**Comment by es128** [comment]
Done with this one... I would suppose the article demos repo should move too? But at this point you may have the ability to do it yourself @tdd.

**Comment by tdd** [comment]
Hey Elan,

The repo could move, yes. But I'm not an admin on the Brunch or per-se, just admin per-repo. So I'll give you admin rights over it and you can proceed as you did for brunch-guide.

**Comment by tdd** [comment]
Done, you can proceed. Do rename it once moved to `brunch-guide-demos`, please. Makes more sense. I'll update my own articles website (js-attitude.fr) to link to the proper one.

**Comment by es128** [comment]
I gave the docs team admin access so I thought that would be a sufficient for a transfer... but nbd I'll take care of it now.

just fyi after this I'll be offline for the most part for the rest of today and this weekend

**Comment by tdd** [comment]
Alright!

**Comment by es128** [comment]
> update my own articles website (js-attitude.fr) to link to the proper one

theoretically github should handle the redirects

**Comment by tdd** [comment]
It does, but might as well have the proper links. Updated on the guide + my article, just now.

**Comment by tdd** [comment]
So before we announce this new guide to the world, any last steps we should take?
- Links from the site / docs?
- Something else?

Elan is AFK until Monday, @paulmillr any ideas on this?

**Comment by paulmillr** [comment]
@tdd this guide should be read by any new folk. Definitely site exposure.

**Comment by tdd** [comment]
Moving the site/docs linking to another issue, closing this one.
