### ISSUE TITLE
How to include CSS from npm modules?

### ISSUE THREAD

**Issue by ivanoats** [deliciousinsights/brunch-guide#18]
Hi, I'm trying to figure out if including CSS from npm modules is something that Brunch supports.

It's really hard to piece together from the guide and issues.

Perhaps an additional section of the guide would be helpful? What do you think? 

I'm just trying to get https://www.npmjs.com/package/skeleton-css included in my brunch build here: 
https://github.com/ivanoats/elm-brunch-starter

**Comment by paulmillr** [comment]
NPM support is a bit broken at this moment. We're fixing it.

**Comment by Anaphase** [comment]
@paulmillr Any progress on this front? Are there any known workarounds aside from copying the CSS out of the `npm_modules/module-name` folder and into the `assets` or `vendor` folders? Obviously that's a crappy solution but it's all I can think of.

**Comment by paulmillr** [comment]
Use `npm.static`.

**Comment by Anaphase** [comment]
Aha, thanks!
