### ISSUE TITLE
Bower package recognition not working

### ISSUE THREAD

**Issue by nicooga** [deliciousinsights/brunch-guide#35]
The compilation fails with a message

error: Resolving deps of app/initialize.js failed. Could not load module 'angular-jsonapi' from '/home/cygnus/Projects/home_accounting_front/app'. Possible solution: add 'angular-jsonapi' to package.json and `npm install`.

I went through the steps described in the FAQ to use bower packages: Run a `bower init` to get my bower.json, added the deps, installed, etc.

The package I'm trying to use [angular-jsonapi](https://github.com/jakubrohleder/angular-jsonapi#synchronizers) has a valid bower.json file with a `main` property.

I saw in this [SO question](http://stackoverflow.com/questions/22825185/how-to-import-bower-components-with-app-built-by-brunch) that brunch gives a very descriptive error message when a bower package does not have a `main` property, so this probably is not the problem.

![captura de pantalla de 2016-04-30 22 20 03](https://cloud.githubusercontent.com/assets/934944/14939534/c95bff90-0f21-11e6-955d-9bee3911d46d.png)

**Comment by paulmillr** [comment]
@goshakkk

**Comment by nicooga** [comment]
The files are being concatenated into vendor.js, and I can even see them in the web inspector. They dont seem to be modulairzed, unlike other packages from npm.
Opened an issue in the wrong repo though.

**Comment by nicooga** [comment]
I think I found out the root of the problem. When I require vedor.js its throws an error:

"Cannot find module 'process' from '/'"

when trying to `process = require('process')`. This makes sense because the server warned that browser.js was compiled but not writen:

``` bash
01 May 03:37:52 - info: application started on http://localhost:3333/
01 May 03:37:54 - warn: /usr/lib/node_modules/brunch/node_modules/deppack/node_modules/node-browser-modules/node_modules/process/browser.js compiled, but not written. Check your javascripts.joinTo config
01 May 03:37:55 - info: compiling
01 May 03:37:55 - info: compiled 17 files into 3 files, copied 2 in 4.3 sec
01 May 03:37:56 - info: copied index.html in 70ms¡
```

**Comment by nicooga** [comment]
Solved. Modified my joinTo config to include that file:

``` coffee
module.exports =
  files:
    javascripts:
      joinTo:
        'vendor.js': /^(bower_components|(\/usr\/lib\/)?node_modules)/
        'app.js': /^app\//
```

**Comment by goshacmd** [comment]
@nicooga in general, it's better to have a local brunch in your project instead of using a global one. That way, the vendor regexp won't have to account for the global location of brunch
