### ISSUE TITLE
Linking to this guide from site/docs

### ISSUE THREAD

**Issue by tdd** [deliciousinsights/brunch-guide#4]
Hey guys, so what should we do before the official announcement of this guide, to make sure it's easily discoverable?
## Links from the site
- [x] Main navbar?
- [x] Replace/complement README link in the home's Getting started section?
- [x] Complement the contents of the home's Documentation section?
- [x] Link to chapter 1 from the bottom of the home's "Why Brunch and not…" section?
## Links from the docs
- [x] Link from the top of `docs/README.md`?
- What else?

**Comment by tdd** [comment]
BTW this takes over that particular task list / reflexion from the last of #1.

Also, I seem to have commit rights to brunch.github.io, so I can handle whatever site tasks we agree on.  On the other hand, I don't have commit rights on `brunch` (rightly so, for now…), so docs tasks are yours, guys :wink:

**Comment by paulmillr** [comment]
1. navbar — yes. 
2. readme — yes
3. yes
4. yes

**Comment by tdd** [comment]
OK, so I'll create an in-repo PR for `brunch.github.io` with these 4 items. And a fork-based PR for the docs item.

**Comment by tdd** [comment]
Hey guys,

So brunch/brunch#952 contains the last item of work for this. The rest (the Brunch site) was done and published.

**Comment by tdd** [comment]
By the way sorry about auto-publishing the links: I thought `grunt publish` just prepped a branch, and by the time I realized it didn't it was too late :unamused:

**Comment by tdd** [comment]
Sweet! So it's all in! Should we get to announcement? I figure the following avenues are nice:

## Stuff I will do
- [x] Tag the current guide as v1.7.20, so 1.7.x users can easily get "their" version if they can't upgrade for some reason.
- [x] Once 1.8 is out, carefully review the changelog and adjust any relevant part of the guide.
- [x] Announce in on my own Twitter feeds (porteneuve, jsattitude, nodeschoolparis), using scheduled tweet campaigns (FR/EN on porteneuve, FR-only on the others)
- [x] Put a block at the top of the original, French article saying future updates and extra contents are to be looked for in the guide (and linking, of course)
- [x] Post on Hackernews at a carefully chosen time of day
- [x] Post on Reddit (/r/javascript, /r/nodejs) at a carefully chosen time of day
- [x] Submit this to DailyJS
- [x] Submit this to JSWeekly
- [x] Submit this to HTML5Weekly
- [x] Submit this to NodeWeekly

## Stuff you can do
- [x] Announce a couple times (scheduled?) on Brunch's twitter account / your accounts?
- What else…?

**Comment by paulmillr** [comment]
@tdd a quick thing. Can we do the next day after 1.8 release (which would be today)? We can update it just in place, a few important & useful changes.

I'll post it under my twitter account and under brunch account, would retweet with others.

**Comment by paulmillr** [comment]
Also, Hacker News.

**Comment by tdd** [comment]
@paulmillr No problem at all, we can even defer that to later this week, as I might be too caught up tonight and tomorrow to have enough time to sift through 1.8 changelog and adjust the guide properly in both languages.

I'll tag the current guide as v1.7.20 to start with, so people can refer to it if need be.

**Comment by tdd** [comment]
Oh and by Reddit, I did mean HN :joy: 

It seems lots of people use this interchangeably, and not being a regular user of either, I find it hard to tell which is which (and which is best for what) :smile:

**Comment by paulmillr** [comment]
r/javascript / r/nodejs should work great too!

**Comment by paulmillr** [comment]
Let's do the release for this thing! 1.8 is finally out after all.

**Comment by tdd** [comment]
Hey! Yes, it's out, but the guide hasn't been updated yet. I need to dive into the specifics of `node_modules` integration, mostly. The rest of the updates are tiny.

I'm a bit underwater just now, as my firstborn son arrived 9 days ago :smile: — Will try to work on this before the week is over, though.

**Comment by tdd** [comment]
Hey @paulmillr @es128 I've been browsing the source code for node_modules handling, and I'm a bit confused as to how it behaves.

It seems that it only ever watches a module's main/`index.js` file, and only adds that in the bundle? I fail to see where it gets the other files to bundle in, be it a static filetree traversal, or a dynamic `require(…)` analysis, a la Browserify or Webpack.

Do we have an up-to-date spec doc somewhere for this? Is this documented anywhere in a comprehensive manner (which this guide would have to do, too)?

Proper `node_modules` handling, esp. wrt isomorphic JS, is still the main reason people stay away from Brunch in favor of Browserify or Webpack. But from my first dive into it, it seems to me the new handling of `node_modules` is rather sub-par here.  What am I missing?!

Cheers,

**Comment by es128** [comment]
cc @yavorsky

**Comment by paulmillr** [comment]
I think we can release the guide with the bower integration as-is. Node modules still require some polishing and not all packages do support it.

Hey @tdd congratz on your newborn!

**Comment by tdd** [comment]
yeah, we should leave npm integration for now. It's actually quite abrasive, I keep getting e-mails and Disqus comments by people who get into all sorts of trouble / confusion using it right now.

We definitely need to huddle sometime soon (Gitter for this repo, maybe?) and hash out:
- How it works now, in detail
- How it could be improved (and whether it's planned / what the ETA might be)

For now, let me just give a look-over on the guide to make sure it's up to date on other issues (e.g. new server config / code, etc.) then we can fire up the comm'.

**Comment by tdd** [comment]
OK so now the guide is updated, let's execute on https://github.com/brunch/brunch-guide/issues/4#issuecomment-90552499
- I'm dealing with pending items 1 and 2 (my own feeds, my original FR article) today.
- I can also find time to submit info about the guide to the newsletters (DailyJS, xWeekly)
- However, I think your (@paulmillr, @es128) posting to HN and Reddit would carry more weight, as creator(s) of the project. If anything, Paul, your karma there's 735 while mine is just 82, having posted there only a couple times.
- What would the best times be for such postings? They only let you post a given URL once, so careful scheduling is essential to get it rolling.
- Also, can you guys schedule a tweet campaign on the official Brunch account? And perhaps RT these from yours?

**Comment by tdd** [comment]
Today's DailyJS: http://dailyjs.com/2015/06/02/wallaby-js-brunch/

**Comment by paulmillr** [comment]
I'll send it to Twitter and HN today. Could someone do it for the reddit?

**Comment by tdd** [comment]
Hey Paul,

Have you sent it to HN? Can't find it. Will send to Reddit now.

**Comment by tdd** [comment]
Also, Peter C from Xxx Weekly got the message, will investigate and likely write about it.

**Comment by tdd** [comment]
- /r/javascript : https://www.reddit.com/r/javascript/comments/38nnid/brunch_the_frontend_app_build_tool_has_a_spiffy/
- /r/node : it won't let me cross-post there. Perhaps an issue with my brand-new profile?

**Comment by paulmillr** [comment]
@tdd @es128 please upvote it on HN.

**Comment by tdd** [comment]
Just did, and spread the word to help!

**Comment by tdd** [comment]
You might want to do the same on the Reddit post (linked earlier)

**Comment by paulmillr** [comment]
Done.

**Comment by paulmillr** [comment]
woah

![screen shot 2015-06-05 at 6 33 57 pm](https://cloud.githubusercontent.com/assets/574696/8009449/7921c6f0-0bb1-11e5-9826-851ed5520c5e.png)

**Comment by paulmillr** [comment]
Except that direct link upvotes don't count :cry:

**Comment by paulmillr** [comment]
Congratz everyone, we've made it. Trending on HN for 1.5h.

**Comment by tdd** [comment]
Ha! Yeah, RTs by Brendan tend to help. I'm fortunate enough that he follows me, knows me well and respects my work, so sometimes this happens.

Great to see Brunch trending on HN. Barely 4 on Reddit, but hey.
