### ISSUE TITLE
Thanx a million !

### ISSUE THREAD

**Issue by khaledMohammed000** [deliciousinsights/brunch-guide#43]
**Sorry for creating an Issue to communicate**

am a newbie to webdev and was getting bored of continuous saving+refreshing thing ! So started to look for automation and **_found gulp , it took away 3-4 days of my productive time but didnt gain much_** , I found your page referenced in **CSS-Tricks** and thought of looking what you can offer and Damn , in **5 minutes** i had the live reload thing up and running !

**Cheers Guys great job !**

**Comment by paulmillr** [comment]
Thanks Khaled! 👍
