### ISSUE TITLE
Page Not found Error for link to docs page

### ISSUE THREAD

**Issue by nikhilshagri** [deliciousinsights/brunch-guide#48]
[This](https://github.com/brunch/brunch-guide/blob/master/content/en/chapter03-conventions-and-defaults.md) page contains a link to the docs page in the first couple of lines; which I suspect might have been moved. If I'm right, this should be pointing to the docs [here](http://brunch.io/docs/getting-started).

**Comment by paulmillr** [comment]
fixed
