### ISSUE TITLE
Wrong regexp in chapter 5

### ISSUE THREAD

**Issue by aMarCruz** [deliciousinsights/brunch-guide#6]
In the guide,
brunch-guide/content/en/chapter05-using-third-party-registries.md
brunch-config.coffee code block

``` coffee
  ....
    javascripts: joinTo:
      'libraries.js': /^(?!app\/)/
      'app.js': /^app\//
  ....
```

produces one unique file: 'libraries.js' (with application.js and jquery.js)
... app.js is missing :(

Windows 7, 32bits, brunch v1.8

**Comment by es128** [comment]
I'd guess it's slash vs backslash biting again. I think I'll be able to solve this in anymatch so there won't be a need to update the guide. 

In the meantime you should be able to solve this by replacing `\/` in the regexes with `[\\\/]`

**Comment by aMarCruz** [comment]
yes, this is working:

``` coffee
    'libraries.js': /^(?!app[\\\/])/
    'app.js': 'app/**'
```

**Comment by es128** [comment]
I wonder if the guide would be better off leaning toward globs for the examples as they may be more understandable to beginners and people coming from grunt/gulp

@aMarCruz for the first one you may be able to also use `'!app/**'`

**Comment by aMarCruz** [comment]
@es128 rou're right! thanks.

**Comment by tdd** [comment]
btw @aMarCruz does the slash-based regex still b0rk on Windows with Brunch 1.8+?  It's supposed to use an updated `minimatch` that normalizes slashes and backslashes, IIRC.

**Comment by es128** [comment]
Yes that should be resolved: https://github.com/es128/anymatch/pull/7
